Adyen Magento Express Checkout 2.0.0
Adyen/adyen-magento2-express-checkout pull request #56
Opened 2023-11-08 14:52 UTC by RokPopov

- #28 
- #44 
- #48 
- #53

2023-11-08 18:55 UTC, candemiralp requested changes

2023-11-08 18:55 UTC, candemiralp commented on composer.json
> +    "adyen/module-payment": "*"
```suggestion
    "adyen/module-payment": "^9"
```

2023-11-09 08:20 UTC, hossam-adyen commented on view/frontend/web/js/googlepay/button.js
> +
```suggestion
```

2023-11-09 08:47 UTC, candemiralp approved these changes

2023-11-28 15:01 UTC, khushboo-singhvi approved these changes

2023-11-28 15:04 UTC, hossam-adyen approved these changes

2023-11-29 10:06 UTC, merged